### ISSUE TITLE
webupdate

### ISSUE THREAD

**Issue by kiralikbeyin** [HomeACcessoryKid/ota#2]
Can you make an webupdate version like this?
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WebServer/examples/WebUpdate/WebUpdate.ino

**Comment by HomeACcessoryKid** [comment]
Anyone could. But my OTA code has so many more benefits that I won’t bother.

Note that this repository (ota) is the experimental corner of the repository life-cycle-manager.
I’m still not sure which name will become the final one.
