### ISSUE TITLE
Ota does not start if wifi network choosen is open (without password)

### ISSUE THREAD

**Issue by RobertoOrioli** [HomeACcessoryKid/ota#7]
Click on Join button seems ineffective ih this case.

**Comment by HomeACcessoryKid** [comment]
Could you open this issue in life-cycle-manager?

Besides that, I am using the maximkulkin/wifi-config repo. Can you reproduce it there? Then also open it there as an issue. 

Thanks for reporting!

**Comment by RobertoOrioli** [comment]
> Could you open this issue in life-cycle-manager? Besides that, I am using the maximkulkin/wifi-config repo. Can you reproduce it there? Then also open it there as an issue. Thanks for reporting!

Here it is: https://github.com/HomeACcessoryKid/life-cycle-manager/issues/19

I'll try to reproduce with the maximkulkin/wifi-config repo... it may be enough to include updated library?

Thanks for your feedback.
